### ISSUE TITLE
Breaks if the last character in file is "

### ISSUE THREAD

**Issue by goodoldgrim** [frozax/fgCSVReader#1]
I'm not sure what purpose the double quote check in line 44 does, but it causes an out of bounds exception if the file ends with quotes.

**Comment by frozax** [comment]
It's supposed to detect strings such as: "i type a double quote "" inside a cell"
The "double double-quote" espaces a double quote.
Can you make a tiny csv and check if it's properly formed?

**Comment by goodoldgrim** [comment]
My test csv looked like so:

A,"spacetest "
B,"break

test"

But as far as I can tell, the exception will trigger every time if the file ends with closing quotes, because if it encounters quotes while inside_quotes == true, it attempts to read the next character.

For my case, I didn't need the extra quote check, so I worked around it by removing the check and inserting another callback if (cur_file_index == file_length) on closing quotes.

**Comment by frozax** [comment]
You're right. I have the following in my latest version locally:

```
    if (cur_file_index == file_length)
    {
        // end of file
        inside_quotes = false;
        goto case '\n';
    }
    else if (file_contents[cur_file_index] == '"')
    {
        // double quote, save one
        cur_item.Append("\"");
        cur_file_index++;
    }
    else
    {
        // leaving quotes section
        inside_quotes = false;
    }
```

I don't use C# anymore, and I forgot to update this code. (http://www.frozax.com/blog/2015/11/why-i-stopped-using-unity3d-after-two-months-and-a-working-prototype/)
